const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
setTimeout(()=>$("#splash").remove(),2800);
$("#menu").onclick=()=>$("#nav").classList.toggle("open");$$("nav a").forEach(a=>a.onclick=()=>$("#nav").classList.remove("open"));
const qs=[
["Seu parceiro pede sua senha porque diz que “casal não deveria ter segredos”. Depois, começa a cobrar respostas e localização.",["Cuidado","Sinal de alerta","Violência"],1,"Exigir acesso, monitorar e cobrar constantemente pode formar um padrão de controle. Observe o contexto e a repetição."],
["Um amigo faz uma piada humilhante sobre você. Você demonstra desconforto e ele responde: “Foi só brincadeira, você é sensível demais”.",["Brincadeira normal","Sinal de alerta","Pode ser violência"],2,"Quando a brincadeira humilha, expõe ou continua apesar do desconforto, o rótulo de brincadeira não elimina o impacto."],
["Uma pessoa diz: “Se você realmente me amasse, faria isso por mim”, tentando pressionar o parceiro.",["Prova de amor","Sinal de alerta","Pode ser chantagem emocional"],2,"Usar culpa ou a necessidade de provar amor para conseguir obediência pode fazer parte de uma dinâmica de manipulação."],
["Um colega compartilha uma foto sua em um grupo sem autorização e diz que “todo mundo faz isso”.",["Normal na internet","Sinal de alerta","Pode violar privacidade"],2,"Compartilhar conteúdo sem consentimento pode violar privacidade e, dependendo do contexto, ter consequências legais."],
["Uma chefe humilha repetidamente um funcionário na frente da equipe e usa a posição para intimidá-lo.",["Liderança firme","Sinal de alerta","Pode caracterizar assédio moral"],2,"Humilhações e constrangimentos repetidos no trabalho podem caracterizar assédio moral, conforme as circunstâncias."],
["Um parceiro tenta afastar a pessoa de amigos e familiares, dizendo que “ninguém entende a relação como ele”.",["Proteção","Sinal de alerta","Isolamento pode ser controle"],2,"Enfraquecer sistematicamente a rede de apoio pode aumentar a dependência e fazer parte de um padrão de controle."]
];
let qi=0,pts=0,done=false;
function render(){let q=qs[qi];$("#step").textContent=`${String(qi+1).padStart(2,"0")} / 06`;$("#score").textContent=`${pts} ${pts==1?"ponto":"pontos"}`;$("#bar").style.width=`${qi/6*100}%`;$("#question").textContent=q[0];$("#answers").innerHTML="";$("#feedback").classList.add("hidden");$("#next").classList.add("hidden");done=false;q[1].forEach((t,i)=>{let b=document.createElement("button");b.className="answer";b.textContent=t;b.onclick=()=>answer(i,b);$("#answers").appendChild(b)})}
function answer(i,b){if(done)return;done=true;let q=qs[qi];$$(".answer").forEach((x,j)=>{x.disabled=true;if(j===q[2])x.classList.add("good")});if(i===q[2]){pts++;b.classList.add("good")}else b.classList.add("bad");$("#score").textContent=`${pts} ${pts==1?"ponto":"pontos"}`;$("#feedback").innerHTML=`<b>${i===q[2]?"Você percebeu um ponto importante.":"Vale olhar além da primeira impressão."}</b><br>${q[3]}`;$("#feedback").classList.remove("hidden");$("#next").textContent=qi===5?"Ver resultado →":"Próxima situação →";$("#next").classList.remove("hidden")}
$("#next").onclick=()=>{qi++;if(qi<6)render();else{$("#bar").style.width="100%";$("#answers").innerHTML="";$("#next").classList.add("hidden");$("#result").innerHTML=`<b>${pts>=5?"VOCÊ ESTÁ ATENTO.":pts>=3?"VOCÊ ESTÁ PERCEBENDO MAIS.":"AGORA VOCÊ SABE ONDE OLHAR."}</b><br>Você identificou ${pts} de 6 situações. O objetivo não é julgar você: é ampliar seu olhar.`;$("#result").classList.remove("hidden")}};render();
$$(".flip").forEach(c=>c.onclick=()=>{c.classList.toggle("on");c.querySelector("small").textContent=c.classList.contains("on")?c.dataset.text:"clique para revelar"});
let total=0,psych=0;$("#survey").onsubmit=e=>{e.preventDefault();let v=$$("#survey select").map(x=>x.value);if(v.some(x=>!x))return;total++;if(v[0]=="Sim")psych++;$("#total").textContent=total;$("#psych").textContent=Math.round(psych/total*100)+"%";$("#msg").textContent="Percepção registrada nesta sessão.";e.target.reset()};
$$(".commitments button").forEach(b=>b.onclick=()=>{$$(".commitments button").forEach(x=>x.classList.remove("active"));b.classList.add("active");$("#commitment").textContent="✓ Seu compromisso: "+b.dataset.msg;$("#commitment").classList.remove("hidden")});